name: Deploy
on:
  pull_request:
    branches:
        - main
    types:
        - closed
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    env:
      ENV_PATH: .env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: create .env
        run: |
          touch ${{ env.ENV_PATH }}
          echo "${{ secrets.ENV_FILE }}" > ${{ env.ENV_PATH }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Gradle's permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
      - name: Access to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://${{ secrets.AWS_BUCKET_NAME }}/deploy/$GITHUB_SHA.zip
      - name: 🚀 Deploy to EC2 with CodeDeploy
        run: aws deploy create-deployment
          --application-name hello-app-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name hello-app-deploy
          --s3-location bucket=${{ secrets.AWS_BUCKET_NAME }},bundleType=zip,key=deploy/$GITHUB_SHA.zip